// libs/shared/frontend/contacts/react/feature/src/lib/form/form.tsx
import React, { useState } from 'react';
import styles from './form.module.css';
import { useContacts } from '@nexanode/frontend-contacts-react-data-access';
import { IContact } from '@nexanode/domain-interfaces';

/* eslint-disable-next-line */
export interface ContactFormProps {}

export const ContactForm: React.FC<ContactFormProps> = (props) => {
  const { createContact, isLoading } = useContacts();
  const [contact, setContact] = useState<Partial<IContact>>({
    name: '',
    email: '',
    message: '',
  });

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>,
  ) => {
    setContact({ ...contact, [e.target.name]: e.target.value });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    createContact(contact);
  };
  return (
    <div className={styles.contactForm}>
      <h2>Contact Us</h2>
      <form onSubmit={handleSubmit}>
        <div className={styles.formGroup}>
          <label htmlFor="name">Name</label>
          <input
            id="name"
            name="name"
            type="text"
            onChange={handleChange}
            value={contact.name}
            required
          />
        </div>
        <div className={styles.formGroup}>
          <label htmlFor="email">Email</label>
          <input
            id="email"
            name="email"
            type="email"
            onChange={handleChange}
            value={contact.email}
            required
          />
        </div>
        <div className={styles.formGroup}>
          <label htmlFor="message">Message</label>
          <textarea
            id="message"
            name="message"
            onChange={handleChange}
            value={contact.message}
            rows={10}
            required
          />
        </div>
        <button type="submit" disabled={isLoading}>
          {isLoading ? 'Submitting form...' : 'Submit'}
        </button>
      </form>
    </div>
  );
};

export default ContactForm;

// libs/shared/frontend/contacts/ng/feature/src/lib/form/form.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import {
  FormBuilder,
  ReactiveFormsModule,
  UntypedFormGroup,
  Validators,
} from '@angular/forms';
import { ContactsStore } from '@nexanode/frontend-contacts-ng-state';

@Component({
    selector: 'nexanode-contact-form',
    imports: [ReactiveFormsModule],
    templateUrl: './form.component.html',
    styleUrl: './form.component.css',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class ContactFormComponent {
  private readonly store = inject(ContactsStore);
  private readonly fb = inject(FormBuilder);
  selectedContact = this.store.selectedContact;
  isLoading = this.store.isLoading;
  error = this.store.error;
  contactForm: UntypedFormGroup = this.fb.group({
    name: ['', Validators.required],
    email: ['', Validators.required],
    message: ['', Validators.required],
  });

  onSubmit() {
    if (this.contactForm.valid) {
      this.store.createContact(this.contactForm.value);
    }
  }
}

<div class="contact">
  <h2>Contact Us</h2>
  @if (selectedContact()) {
    <p class="success">Thanks for contacting us!</p>
  } @else {
    <form [formGroup]="contactForm" (ngSubmit)="onSubmit()">
      <div class="form-control">
        <label for="name">Name</label>
        <input type="text" id="name" formControlName="name" />
      </div>
      <div class="form-control">
        <label for="email">Email</label>
        <input type="email" id="email" formControlName="email" />
      </div>
      <div class="form-control">
        <label for="message">Message</label>
        <textarea id="message" formControlName="message" rows="10"></textarea>
      </div>
      <div>
        <button type="submit" [disabled]="contactForm.invalid">
          {{ isLoading() ? 'Submitting...' : 'Submit' }}
        </button>
      </div>
    </form>
  }
</div>
